# Generated by Django 5.2 on 2025-04-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Travel', '0005_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
